// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLSzEHFwshOfn-_EIsATzU2sYsMrIwnNs',
    appId: '1:505413136406:web:b7920a164db5de635d8537',
    messagingSenderId: '505413136406',
    projectId: 'expense-tracker-6f119',
    authDomain: 'expense-tracker-6f119.firebaseapp.com',
    storageBucket: 'expense-tracker-6f119.firebasestorage.app',
    measurementId: 'G-Y9NRCCH6JY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz96t_U2TUuoB7FsfRNFjo051T__3RPrY',
    appId: '1:505413136406:android:b04895b557f8217d5d8537',
    messagingSenderId: '505413136406',
    projectId: 'expense-tracker-6f119',
    storageBucket: 'expense-tracker-6f119.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9fAe4b5SGncMwvjTAVU6N_QDQgGbUtcs',
    appId: '1:505413136406:ios:563a51fcdc0759d35d8537',
    messagingSenderId: '505413136406',
    projectId: 'expense-tracker-6f119',
    storageBucket: 'expense-tracker-6f119.firebasestorage.app',
    androidClientId: '505413136406-33qf25n5n8gnlu1gpma736hj10ar9vqg.apps.googleusercontent.com',
    iosClientId: '505413136406-1hrm3e8s5vr9u010p98o0bn2qkeqsash.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloWorld',
  );
}
